---
entrada_webs_git_branch: master
entrada_webs_git_domain: gitlab.com
#entrada_webs_git_user: override-this-user!!!
#entrada_webs_git_password: override-this-password!!!
entrada_webs_git_repo: nagruta/entrada.git
entrada_webs_path_work: es/nagruta/entrada
entrada_webs_run_type: erlang
#entrada_webs_service_name: default-is-undefined
#entrada_webs_service_command: default-is-undefined
entrada_webs_dir_top:  "{{ entrada_user_dir_d }}"
entrada_webs_dir_work: "{{ entrada_webs_dir_top }}/{{ entrada_webs_path_work }}"
entrada_webs_dir_cert: "{{ entrada_webs_dir_work }}/cert"
entrada_webs_dir_run:  "{{ entrada_webs_dir_work }}/{{ entrada_webs_path_run }}"
