---
- name: "user {{ entrada_user_name }}"
  user:
    name: "{{ entrada_user_name }}"
    password: "{{ entrada_user_password }}"
    shell: /bin/dash
    uid: "{{ entrada_user_uid }}"
  become: yes

- name: "user {{ entrada_user_name }} .bashrc PATH to elo"
  block:
  - file:
      path: "{{ entrada_user_dir_elo }}"
      state: directory
  - lineinfile:
      line: 'PATH={{ entrada_user_dir_elo }}:$PATH'
      path: "{{ entrada_user_dir_home }}/.bashrc"
  - lineinfile:
      state: absent
      line: 'PATH={{ entrada_user_dir_elo }}:$PATH'
      path: "{{ entrada_user_dir_home }}/.profile"
  become: yes
  become_user: "{{ entrada_user_name }}"
