#!/bin/bash
if [ $# -lt 1 ]
then
    echo usage: "$0 <host pattern> <variable name>"
    exit 1
fi
RESULT=$(`dirname $0`/adhoc $1 -m debug -a '"var='$2'"')
#echo "RESULT >"$RESULT"<"
[[ $RESULT =~ \"$2\":\ \"(.*)\" ]]
VAR=${BASH_REMATCH[1]}
echo $VAR
