#!/bin/bash
if [ $# -lt 1 ]
then
    echo usage: "$0 <ansible command>"
    exit 1
fi
PATH_THIS=`dirname $0`
source $PATH_THIS/env-ansible
#echo "ARGS >"$@"<"
#COMMAND="ansible -i "$FILE_INVENTORY" "$ARG_EXTRA_VARS" -vv "$@""
#echo "COMMMAND >"$COMMAND"<"
eval ansible -i $FILE_INVENTORY $ARG_EXTRA_VARS "$@"
