#!/bin/sh
if [ $# -lt 1 ]; then
  echo usage: "$0 <host pattern>"
  exit 1
fi
PATH_HERE=$(pwd)/$(dirname $0)
USER=$($PATH_HERE/adhoc-var $1 "ansible_user")
HOST=$($PATH_HERE/adhoc-var $1 "ansible_host")
PASSWORD=$($PATH_HERE/adhoc-var $1 "ansible_password")
echo "$USER@$HOST   password: "$PASSWORD
ssh $USER@$HOST
