#!/bin/bash
if [ $# -lt 2 ]
then
    echo usage: "$0 <name> <value>"
    exit 1
fi
PATH_THIS=`dirname $0`
. $PATH_THIS/cd-env-ansible
ansible-vault encrypt_string $ARG_VAULT_PASSWORD_FILE $2 --name $1 $3 $4 $5 $6 $7 $8 $9
