#!/bin/bash
if [ $# -lt 1 ]
then
    echo usage: "$0 <playbook name between apb-???.yml>"
    exit 1
fi
source `dirname $0`/env-ansible
ansible-playbook -i $FILE_INVENTORY $ARG_EXTRA_VARS -vv apb-$1.yml $2 $3 $4 $5 $6 $7 $8 $9
