---
all:
  hosts:
    host_example_01:
      ansible_host: 192.168.9.1
    host_example_02:
      ansible_host: 192.168.9.2
    host_example_03:
      ansible_host: 192.168.9.3
    host_example_04:
      ansible_host: 192.168.9.4
    host_example_05:
      ansible_host: 192.168.9.5
    host_example_06:
      ansible_host: 192.168.9.6
  children:
    group_os_debian:
      children:
        # !!! isolate group down one level down to prevent var overrides
        group_os_debian_vars:
          vars:
            ansible_user: admin
          hosts:
            host_example_01:
            host_example_02:
    group_os_macos:
      children:
        # !!! isolate group down one level down to prevent var overrides
        group_os_macos_vars:
          vars:
            ansible_user: macgod
          hosts:
            host_example_05:
            host_example_06:
    group_os_ubuntu:
      children:
        # !!! isolate group down one level down to prevent var overrides
        group_os_ubuntu_vars:
          vars:
            ansible_user: ubuntu
          hosts:
            host_example_03:
            host_example_04:
    group_purpose_backrest:
      children:
        # !!! isolate group down one level down to prevent var overrides
        group_purpose_backrest_vars:
          vars:
          hosts:
            host_example_01:
    group_purpose_frontweb:
      children:
        group_purpose_frontweb_nodejs:
          children:
            # !!! isolate group down one level down to prevent var overrides
            group_purpose_frontweb_nodejs_vars:
              vars:
              hosts:
                host_example_02:
    group_purpose_macprog:
      children:
        # !!! isolate group down one level down to prevent var overrides
        group_purpose_macprog_vars:
          vars:
          hosts:
            host_example_05:
            host_example_06:
    group_purpose_scpfiles:
      children:
        # !!! isolate group down one level down to prevent var overrides
        group_purpose_scpfiles_vars:
          vars:
          hosts:
            host_example_03:
    group_purpose_stunturn:
      children:
        # !!! isolate group down one level down to prevent var overrides
        group_purpose_stunturn_vars:
          vars:
          hosts:
            host_example_04:
...
