---
# derived from https://github.com/wjoel/ansible-jenkins-pipeline/blob/master/tasks/main.yml

- name: Get Jenkins crumb
  uri:
    user: "{{ entrada_user_name }}"
    password: "{{ entrada_user_password }}"
    force_basic_auth: yes
    url: "http://127.0.0.1:8080/crumbIssuer/api/json"
    return_content: yes
    status_code: 200, 404
  register: jenkins_crumb
  until: jenkins_crumb.status == 200 and jenkins_crumb.content.find('Please wait while Jenkins is getting ready to work') == -1
  retries: 10
  delay: 5

- name: Set crumb header
  set_fact:
    jenkins_crumb_header: "{{ jenkins_crumb.json.crumbRequestField }}"

- name: Set crumb value
  set_fact:
    jenkins_crumb_value: "{{ jenkins_crumb.json.crumb }}"

- name: Set crumb token
  set_fact:
    jenkins_crumb_token: "{{ jenkins_crumb_header }}={{ jenkins_crumb_value }}"

# derived from https://github.com/wjoel/ansible-jenkins-pipeline/blob/master/tasks/seed-job.yml

- name: Get list of jobs
  uri:
    user: "{{ entrada_user_name }}"
    password: "{{ entrada_user_password }}"
    force_basic_auth: yes
    url: "http://127.0.0.1:8080/api/json?tree=jobs[name]"
    return_content: yes
  register: jenkins_jobs
  until: jenkins_jobs.content.find('Please wait while Jenkins is getting ready to work') == -1
  retries: 10
  delay: 5

- name: Check if seed job exists
  set_fact:
    jenkins_seed_job_exists: "{{ entrada_jenkins_job_name_seed in (jenkins_jobs.content|from_json).jobs|map(attribute='name')|list }}"

- name: Create seed job
  uri:
    user: "{{ entrada_user_name }}"
    password: "{{ entrada_user_password }}"
    force_basic_auth: yes
    #url: "http://127.0.0.1:8080/createItem?name={{ entrada_jenkins_job_name_seed }}&{{ jenkins_crumb_token }}"
    url: "http://127.0.0.1:8080/createItem?name={{ entrada_jenkins_job_name_seed }}"
    method: POST
    headers:
      Content-Type: "application/xml"
      Jenkins-Crumb: "{{ jenkins_crumb_value }}"
    body: "{{ lookup('template', entrada_jenkins_template_seed) }}"
  register: jenkins_seed_job_created
  when: not jenkins_seed_job_exists

- name: Update seed job
  uri:
    user: "{{ entrada_user_name }}"
    password: "{{ entrada_user_password }}"
    force_basic_auth: yes
    #url: "http://127.0.0.1:8080/job/{{ entrada_jenkins_job_name_seed }}/config.xml?{{ jenkins_crumb_token }}"
    url: "http://127.0.0.1:8080/job/{{ entrada_jenkins_job_name_seed }}/config.xml"
    method: POST
    headers:
      Content-Type: "application/xml"
      Jenkins-Crumb: "{{ jenkins_crumb_value }}"
    body: "{{ lookup('template', entrada_jenkins_template_seed) }}"
  register: jenkins_seed_job_updated
  when: jenkins_seed_job_exists

- name: Run seed job
  uri:
    user: "{{ entrada_user_name }}"
    password: "{{ entrada_user_password }}"
    force_basic_auth: yes
    #url: "http://127.0.0.1:8080/job/{{ entrada_jenkins_job_name_seed }}/build?{{ jenkins_crumb_token }}"
    url: "http://127.0.0.1:8080/job/{{ entrada_jenkins_job_name_seed }}/build"
    method: POST
    headers:
      Jenkins-Crumb: "{{ jenkins_crumb_value }}"
    status_code: 201
  register: jenkins_seed_job_started
  when: jenkins_seed_job_created|success or jenkins_seed_job_updated|success

- name: Wait for seed job
  uri:
    user: "{{ entrada_user_name }}"
    password: "{{ entrada_user_password }}"
    force_basic_auth: yes
    #url: "http://127.0.0.1:8080/job/{{ entrada_jenkins_job_name_seed }}/lastBuild/buildNumber?{{ jenkins_crumb_token }}"
    url: "http://127.0.0.1:8080/job/{{ entrada_jenkins_job_name_seed }}/lastBuild/buildNumber"
    method: GET
    headers:
      Jenkins-Crumb: "{{ jenkins_crumb_value }}"
    status_code: 200
  register: jenkins_seed
  until: jenkins_seed['status']|default(0) == 200
  retries: 10
  delay: 5
