---
- name: service restart
  service: name=jenkins state=restarted

# TODO: Ubunutu 20.04 is returning SSL: WRONG VERSION NUMBER
#- name: wait for service
#  uri:
#    url: https://localhost:8080
#    validate_certs: no
#    timeout: 5
#  register: result
#  until: result.status == 200
#  retries: 60
#  delay: 1

- name: wait for service (### hack delay)
  wait_for: timeout=30
  delegate_to: localhost
