---
- name: establish credentials
  jenkins_script:
    script: |
      import jenkins.model.*
      import com.cloudbees.plugins.credentials.CredentialsProvider
      import com.cloudbees.plugins.credentials.CredentialsScope
      import com.cloudbees.plugins.credentials.common.StandardUsernameCredentials
      import com.cloudbees.plugins.credentials.domains.Domain
      import com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl
      def domain = Domain.global()
      def instance = Jenkins.instance
      def credstore = instance.getExtensionList(
          'com.cloudbees.plugins.credentials.SystemCredentialsProvider'
          )[0].getStore()
      def oldCreds = CredentialsProvider.lookupCredentials(
          StandardUsernameCredentials.class, instance).findResult {
              it.username == '${username}' ? it : null
          }
      def newCreds = new UsernamePasswordCredentialsImpl(
          CredentialsScope.GLOBAL, '${credsid}',
          '${description}', '${username}', '${password}')
      if (oldCreds) {
          credstore.updateCredentials(domain, oldCreds, newCreds)
      } else {
          credstore.addCredentials(domain, newCreds)
      }
    args:
      credsid: "{{ item.credsid }}"
      description: "entrada credential"
      username: "{{ item.username }}"
      password: "{{ item.password }}"
    user: "{{ entrada_user_name }}"
    password: "{{ entrada_user_password }}"
  with_items: "{{ entrada_cicd_credentials }}"
