---
# https://askubuntu.com/questions/911863/where-does-netfilter-persistent-save-the-iptables-rules
- name: install iptables-persistent
  apt: name=iptables-persistent update_cache=yes
  become: yes

- name: service netfilter-persistent
  service: name=netfilter-persistent state=started

- name: iptables accept 80 (HTTP)
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '80'
    jump: ACCEPT
  become: yes
  register: result_http_accept

- name: iptables accept 443 (HTTP)
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '443'
    jump: ACCEPT
  become: yes
  register: result_https_accept

# !!! redirect jenkins because non-root cannot bind ports < 1024
- name: iptables redirect port 80 (HTTP) to 8080 (Jenkins default)
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth0
    protocol: tcp
    match: tcp
    destination_port: '80'
    jump: REDIRECT
    to_ports: '8080'
  become: yes
  register: result_http_redirect

- name: iptables redirect port 443 (HTTPS) to 8443
  iptables:
    table: nat
    chain: PREROUTING
    in_interface: eth0
    protocol: tcp
    match: tcp
    destination_port: '443'
    jump: REDIRECT
    to_ports: '8443'
  become: yes
  register: result_https_redirect

- name: iptables save (Ubuntu)
  shell: "netfilter-persistent save"
  become: yes
  when: result_http_accept.changed or
        result_https_accept.changed or
        result_http_redirect.changed or
        result_https_redirect.changed
