---
- name: "copy extra file {{ entrada_webs_extra_file_name }}"
  vars:
    srcfile: "{{ scppath }}{{ entrada_webs_extra_file_name }}"
    destparent: "{{ entrada_user_home_webs_run_dir }}/{{ entrada_webs_extra_file_path }}"
    target: "{{ destparent }}{{ entrada_webs_extra_file_name }}"
    replacetarget: no
  include_role:
     name: filecopy
     tasks_from: atasks-establish-file.yml
  when: entrada_webs_extra_file_name is defined and
        entrada_webs_extra_file_path is defined and
        entrada_user_home_webs_run_dir is defined
