---
- name: "establish website"
  vars:
    entrada_user_home_top_dir: "/home/{{ entrada_user_name }}/{{ entrada_user_top_dir }}"
    entrada_user_home_work_dir: "{{ entrada_user_home_top_dir }}/{{ entrada_webs_git_work_dir }}"
  block:
  - set_fact:
      entrada_webs_git_url_prefix: ""

  - name: "prefix git URL with user:password"
    set_fact:
      entrada_webs_git_url_prefix: "{{ entrada_webs_git_user }}:{{ entrada_webs_git_password|urlencode() }}@"
    when: entrada_webs_git_user is defined and entrada_webs_git_password is defined

  - name: "clone/checkout repo"
    git:
      #key_file: "{{ entrada_webs_git_key_file }}"
      repo: "https://{{ entrada_webs_git_url_prefix }}{{ entrada_webs_git_domain }}//{{ entrada_webs_git_repo }}"
      dest: "{{ entrada_user_home_work_dir }}"
    become: yes

  - name: "reset top directory owner"
    file:
      dest: "{{ entrada_user_home_top_dir }}"
      owner: "{{ entrada_user_name }}"
      group: "{{ entrada_user_name }}"
      recurse: yes
    become: yes
