---
- set_fact:
    entrada_webs_git_url_prefix: ""

- name: "prefix git URL with user:password"
  set_fact:
    entrada_webs_git_url_prefix: "{{ entrada_webs_git_user }}:{{ entrada_webs_git_password|urlencode() }}@"
  when: entrada_webs_git_user is defined and entrada_webs_git_password is defined

- name: "clone/checkout repo"
  git:
    #key_file: "{{ entrada_webs_git_key_file }}"
    repo: "https://{{ entrada_webs_git_url_prefix }}{{ entrada_webs_git_domain }}//{{ entrada_webs_git_repo }}"
    dest: "{{ entrada_user_home_work_dir }}"
    version: "{{ entrada_webs_git_branch }}"
    force: yes
  become: yes

- name: "copy letsencrypt certificates to {{ entrada_user_home_webs_run_dir }}"
  block:
    - copy:
        src: "/etc/letsencrypt/live/{{ entrada_webs_cert_domain }}/fullchain.pem"
        dest: "{{ entrada_user_home_webs_run_dir }}/cert/"
        remote_src: yes
    - copy:
        src: "/etc/letsencrypt/live/{{ entrada_webs_cert_domain }}/privkey.pem"
        dest: "{{ entrada_user_home_webs_run_dir }}/cert/"
        remote_src: yes
    - file:
        dest: "{{ entrada_user_home_webs_run_dir }}/cert/privkey.pem"
        mode: 0600
  become: yes
  when: entrada_webs_run_dir is defined

- name: "reset top directory owner, recursively"
  file:
    dest: "{{ entrada_user_home_top_dir }}"
    owner: "{{ entrada_user_name }}"
    group: "{{ entrada_user_name }}"
    recurse: yes
  become: yes

- name: "npm install package.json in {{ entrada_user_home_webs_run_dir }}"
  npm: path={{ entrada_user_home_webs_run_dir }}
  become: yes
  become_user: "{{ entrada_user_name }}"
  when: entrada_webs_run_dir is defined
