---
- include_tasks: atasks-webgit.yml
- include_tasks: atasks-extrafile.yml

- name: "copy letsencrypt certificates to {{ entrada_webs_dir_run }}"
  block:
    - copy:
        src: "/etc/letsencrypt/live/{{ entrada_webs_cert_domain }}/fullchain.pem"
        dest: "{{ entrada_webs_dir_run }}/cert/"
        remote_src: yes
    - copy:
        src: "/etc/letsencrypt/live/{{ entrada_webs_cert_domain }}/privkey.pem"
        dest: "{{ entrada_webs_dir_run }}/cert/"
        remote_src: yes
    - file:
        dest: "{{ entrada_webs_dir_run }}/cert/privkey.pem"
        mode: 0600
  become: yes
  when: entrada_webs_dir_run is defined and entrada_webs_cert_enable is defined and entrada_webs_cert_enable

- name: "reset run directory owner, recursively"
  file:
    dest: "{{ entrada_webs_dir_run }}"
    owner: "{{ entrada_user_name }}"
    group: "{{ entrada_user_name }}"
    recurse: yes
  become: yes

- include_tasks: atasks-npm.yml
  when: entrada_webs_run_type == "nodejs" and entrada_webs_dir_run is defined

- name: "establish system service"
  vars:
    entrada_service_name: "{{ entrada_webs_service_name }}"
    entrada_service_user: "{{ entrada_user_name }}"
    entrada_service_path: "{{ entrada_webs_dir_run }}"
    entrada_service_command: "{{ entrada_webs_service_command }}"
  include_role: name=service
  when: entrada_webs_service_name is defined and entrada_webs_service_command is defined
